# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/ubuntu/cmake-3.30.0-rc3-linux-x86_64/bin/cmake

# The command to remove a file.
RM = /home/ubuntu/cmake-3.30.0-rc3-linux-x86_64/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ubuntu/coreMQTT/test

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ubuntu/coreMQTT

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/home/ubuntu/cmake-3.30.0-rc3-linux-x86_64/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/home/ubuntu/cmake-3.30.0-rc3-linux-x86_64/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/home/ubuntu/cmake-3.30.0-rc3-linux-x86_64/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu/coreMQTT/CMakeFiles /home/ubuntu/coreMQTT//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu/coreMQTT/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named coverity_analysis

# Build rule for target.
coverity_analysis: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 coverity_analysis
.PHONY : coverity_analysis

# fast build rule for target.
coverity_analysis/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coverity_analysis.dir/build.make CMakeFiles/coverity_analysis.dir/build
.PHONY : coverity_analysis/fast

#=============================================================================
# Target rules for targets named cmock

# Build rule for target.
cmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cmock
.PHONY : cmock

# fast build rule for target.
cmock/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmock.dir/build.make CMakeFiles/cmock.dir/build
.PHONY : cmock/fast

#=============================================================================
# Target rules for targets named unity

# Build rule for target.
unity: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 unity
.PHONY : unity

# fast build rule for target.
unity/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unity.dir/build.make CMakeFiles/unity.dir/build
.PHONY : unity/fast

#=============================================================================
# Target rules for targets named coverage

# Build rule for target.
coverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 coverage
.PHONY : coverage

# fast build rule for target.
coverage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coverage.dir/build.make CMakeFiles/coverage.dir/build
.PHONY : coverage/fast

#=============================================================================
# Target rules for targets named core_mqtt_mock

# Build rule for target.
core_mqtt_mock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 core_mqtt_mock
.PHONY : core_mqtt_mock

# fast build rule for target.
core_mqtt_mock/fast:
	$(MAKE) $(MAKESILENT) -f unit-test/MQTT/CMakeFiles/core_mqtt_mock.dir/build.make unit-test/MQTT/CMakeFiles/core_mqtt_mock.dir/build
.PHONY : core_mqtt_mock/fast

#=============================================================================
# Target rules for targets named core_mqtt_real

# Build rule for target.
core_mqtt_real: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 core_mqtt_real
.PHONY : core_mqtt_real

# fast build rule for target.
core_mqtt_real/fast:
	$(MAKE) $(MAKESILENT) -f unit-test/MQTT/CMakeFiles/core_mqtt_real.dir/build.make unit-test/MQTT/CMakeFiles/core_mqtt_real.dir/build
.PHONY : core_mqtt_real/fast

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) $(MAKESILENT) -f unit-test/MQTT/CMakeFiles/Experimental.dir/build.make unit-test/MQTT/CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) $(MAKESILENT) -f unit-test/MQTT/CMakeFiles/Nightly.dir/build.make unit-test/MQTT/CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) $(MAKESILENT) -f unit-test/MQTT/CMakeFiles/Continuous.dir/build.make unit-test/MQTT/CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) $(MAKESILENT) -f unit-test/MQTT/CMakeFiles/NightlyMemoryCheck.dir/build.make unit-test/MQTT/CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) $(MAKESILENT) -f unit-test/MQTT/CMakeFiles/NightlyStart.dir/build.make unit-test/MQTT/CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) $(MAKESILENT) -f unit-test/MQTT/CMakeFiles/NightlyUpdate.dir/build.make unit-test/MQTT/CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) $(MAKESILENT) -f unit-test/MQTT/CMakeFiles/NightlyConfigure.dir/build.make unit-test/MQTT/CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) $(MAKESILENT) -f unit-test/MQTT/CMakeFiles/NightlyBuild.dir/build.make unit-test/MQTT/CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) $(MAKESILENT) -f unit-test/MQTT/CMakeFiles/NightlyTest.dir/build.make unit-test/MQTT/CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) $(MAKESILENT) -f unit-test/MQTT/CMakeFiles/NightlyCoverage.dir/build.make unit-test/MQTT/CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f unit-test/MQTT/CMakeFiles/NightlyMemCheck.dir/build.make unit-test/MQTT/CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) $(MAKESILENT) -f unit-test/MQTT/CMakeFiles/NightlySubmit.dir/build.make unit-test/MQTT/CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) $(MAKESILENT) -f unit-test/MQTT/CMakeFiles/ExperimentalStart.dir/build.make unit-test/MQTT/CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) $(MAKESILENT) -f unit-test/MQTT/CMakeFiles/ExperimentalUpdate.dir/build.make unit-test/MQTT/CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) $(MAKESILENT) -f unit-test/MQTT/CMakeFiles/ExperimentalConfigure.dir/build.make unit-test/MQTT/CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) $(MAKESILENT) -f unit-test/MQTT/CMakeFiles/ExperimentalBuild.dir/build.make unit-test/MQTT/CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) $(MAKESILENT) -f unit-test/MQTT/CMakeFiles/ExperimentalTest.dir/build.make unit-test/MQTT/CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) $(MAKESILENT) -f unit-test/MQTT/CMakeFiles/ExperimentalCoverage.dir/build.make unit-test/MQTT/CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f unit-test/MQTT/CMakeFiles/ExperimentalMemCheck.dir/build.make unit-test/MQTT/CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) $(MAKESILENT) -f unit-test/MQTT/CMakeFiles/ExperimentalSubmit.dir/build.make unit-test/MQTT/CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) $(MAKESILENT) -f unit-test/MQTT/CMakeFiles/ContinuousStart.dir/build.make unit-test/MQTT/CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) $(MAKESILENT) -f unit-test/MQTT/CMakeFiles/ContinuousUpdate.dir/build.make unit-test/MQTT/CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) $(MAKESILENT) -f unit-test/MQTT/CMakeFiles/ContinuousConfigure.dir/build.make unit-test/MQTT/CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) $(MAKESILENT) -f unit-test/MQTT/CMakeFiles/ContinuousBuild.dir/build.make unit-test/MQTT/CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) $(MAKESILENT) -f unit-test/MQTT/CMakeFiles/ContinuousTest.dir/build.make unit-test/MQTT/CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) $(MAKESILENT) -f unit-test/MQTT/CMakeFiles/ContinuousCoverage.dir/build.make unit-test/MQTT/CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f unit-test/MQTT/CMakeFiles/ContinuousMemCheck.dir/build.make unit-test/MQTT/CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) $(MAKESILENT) -f unit-test/MQTT/CMakeFiles/ContinuousSubmit.dir/build.make unit-test/MQTT/CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

#=============================================================================
# Target rules for targets named core_mqtt_utest

# Build rule for target.
core_mqtt_utest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 core_mqtt_utest
.PHONY : core_mqtt_utest

# fast build rule for target.
core_mqtt_utest/fast:
	$(MAKE) $(MAKESILENT) -f unit-test/MQTT/CMakeFiles/core_mqtt_utest.dir/build.make unit-test/MQTT/CMakeFiles/core_mqtt_utest.dir/build
.PHONY : core_mqtt_utest/fast

#=============================================================================
# Target rules for targets named core_mqtt_state_utest

# Build rule for target.
core_mqtt_state_utest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 core_mqtt_state_utest
.PHONY : core_mqtt_state_utest

# fast build rule for target.
core_mqtt_state_utest/fast:
	$(MAKE) $(MAKESILENT) -f unit-test/MQTT/CMakeFiles/core_mqtt_state_utest.dir/build.make unit-test/MQTT/CMakeFiles/core_mqtt_state_utest.dir/build
.PHONY : core_mqtt_state_utest/fast

#=============================================================================
# Target rules for targets named core_mqtt_serializer_utest

# Build rule for target.
core_mqtt_serializer_utest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 core_mqtt_serializer_utest
.PHONY : core_mqtt_serializer_utest

# fast build rule for target.
core_mqtt_serializer_utest/fast:
	$(MAKE) $(MAKESILENT) -f unit-test/MQTT/CMakeFiles/core_mqtt_serializer_utest.dir/build.make unit-test/MQTT/CMakeFiles/core_mqtt_serializer_utest.dir/build
.PHONY : core_mqtt_serializer_utest/fast

#=============================================================================
# Target rules for targets named core_mqttv5_mock

# Build rule for target.
core_mqttv5_mock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 core_mqttv5_mock
.PHONY : core_mqttv5_mock

# fast build rule for target.
core_mqttv5_mock/fast:
	$(MAKE) $(MAKESILENT) -f unit-test/MQTTv5/CMakeFiles/core_mqttv5_mock.dir/build.make unit-test/MQTTv5/CMakeFiles/core_mqttv5_mock.dir/build
.PHONY : core_mqttv5_mock/fast

#=============================================================================
# Target rules for targets named core_mqttv5_real

# Build rule for target.
core_mqttv5_real: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 core_mqttv5_real
.PHONY : core_mqttv5_real

# fast build rule for target.
core_mqttv5_real/fast:
	$(MAKE) $(MAKESILENT) -f unit-test/MQTTv5/CMakeFiles/core_mqttv5_real.dir/build.make unit-test/MQTTv5/CMakeFiles/core_mqttv5_real.dir/build
.PHONY : core_mqttv5_real/fast

#=============================================================================
# Target rules for targets named core_mqttv5_utest

# Build rule for target.
core_mqttv5_utest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 core_mqttv5_utest
.PHONY : core_mqttv5_utest

# fast build rule for target.
core_mqttv5_utest/fast:
	$(MAKE) $(MAKESILENT) -f unit-test/MQTTv5/CMakeFiles/core_mqttv5_utest.dir/build.make unit-test/MQTTv5/CMakeFiles/core_mqttv5_utest.dir/build
.PHONY : core_mqttv5_utest/fast

#=============================================================================
# Target rules for targets named core_mqttv5_state_utest

# Build rule for target.
core_mqttv5_state_utest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 core_mqttv5_state_utest
.PHONY : core_mqttv5_state_utest

# fast build rule for target.
core_mqttv5_state_utest/fast:
	$(MAKE) $(MAKESILENT) -f unit-test/MQTTv5/CMakeFiles/core_mqttv5_state_utest.dir/build.make unit-test/MQTTv5/CMakeFiles/core_mqttv5_state_utest.dir/build
.PHONY : core_mqttv5_state_utest/fast

#=============================================================================
# Target rules for targets named core_mqttv5_serializer_utest

# Build rule for target.
core_mqttv5_serializer_utest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 core_mqttv5_serializer_utest
.PHONY : core_mqttv5_serializer_utest

# fast build rule for target.
core_mqttv5_serializer_utest/fast:
	$(MAKE) $(MAKESILENT) -f unit-test/MQTTv5/CMakeFiles/core_mqttv5_serializer_utest.dir/build.make unit-test/MQTTv5/CMakeFiles/core_mqttv5_serializer_utest.dir/build
.PHONY : core_mqttv5_serializer_utest/fast

source/core_mqtt.o: source/core_mqtt.c.o
.PHONY : source/core_mqtt.o

# target to build an object file
source/core_mqtt.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coverity_analysis.dir/build.make CMakeFiles/coverity_analysis.dir/source/core_mqtt.c.o
.PHONY : source/core_mqtt.c.o

source/core_mqtt.i: source/core_mqtt.c.i
.PHONY : source/core_mqtt.i

# target to preprocess a source file
source/core_mqtt.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coverity_analysis.dir/build.make CMakeFiles/coverity_analysis.dir/source/core_mqtt.c.i
.PHONY : source/core_mqtt.c.i

source/core_mqtt.s: source/core_mqtt.c.s
.PHONY : source/core_mqtt.s

# target to generate assembly for a file
source/core_mqtt.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coverity_analysis.dir/build.make CMakeFiles/coverity_analysis.dir/source/core_mqtt.c.s
.PHONY : source/core_mqtt.c.s

source/core_mqtt_serializer.o: source/core_mqtt_serializer.c.o
.PHONY : source/core_mqtt_serializer.o

# target to build an object file
source/core_mqtt_serializer.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coverity_analysis.dir/build.make CMakeFiles/coverity_analysis.dir/source/core_mqtt_serializer.c.o
.PHONY : source/core_mqtt_serializer.c.o

source/core_mqtt_serializer.i: source/core_mqtt_serializer.c.i
.PHONY : source/core_mqtt_serializer.i

# target to preprocess a source file
source/core_mqtt_serializer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coverity_analysis.dir/build.make CMakeFiles/coverity_analysis.dir/source/core_mqtt_serializer.c.i
.PHONY : source/core_mqtt_serializer.c.i

source/core_mqtt_serializer.s: source/core_mqtt_serializer.c.s
.PHONY : source/core_mqtt_serializer.s

# target to generate assembly for a file
source/core_mqtt_serializer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coverity_analysis.dir/build.make CMakeFiles/coverity_analysis.dir/source/core_mqtt_serializer.c.s
.PHONY : source/core_mqtt_serializer.c.s

source/core_mqtt_state.o: source/core_mqtt_state.c.o
.PHONY : source/core_mqtt_state.o

# target to build an object file
source/core_mqtt_state.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coverity_analysis.dir/build.make CMakeFiles/coverity_analysis.dir/source/core_mqtt_state.c.o
.PHONY : source/core_mqtt_state.c.o

source/core_mqtt_state.i: source/core_mqtt_state.c.i
.PHONY : source/core_mqtt_state.i

# target to preprocess a source file
source/core_mqtt_state.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coverity_analysis.dir/build.make CMakeFiles/coverity_analysis.dir/source/core_mqtt_state.c.i
.PHONY : source/core_mqtt_state.c.i

source/core_mqtt_state.s: source/core_mqtt_state.c.s
.PHONY : source/core_mqtt_state.s

# target to generate assembly for a file
source/core_mqtt_state.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coverity_analysis.dir/build.make CMakeFiles/coverity_analysis.dir/source/core_mqtt_state.c.s
.PHONY : source/core_mqtt_state.c.s

unit-test/CMock/src/cmock.o: unit-test/CMock/src/cmock.c.o
.PHONY : unit-test/CMock/src/cmock.o

# target to build an object file
unit-test/CMock/src/cmock.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmock.dir/build.make CMakeFiles/cmock.dir/unit-test/CMock/src/cmock.c.o
.PHONY : unit-test/CMock/src/cmock.c.o

unit-test/CMock/src/cmock.i: unit-test/CMock/src/cmock.c.i
.PHONY : unit-test/CMock/src/cmock.i

# target to preprocess a source file
unit-test/CMock/src/cmock.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmock.dir/build.make CMakeFiles/cmock.dir/unit-test/CMock/src/cmock.c.i
.PHONY : unit-test/CMock/src/cmock.c.i

unit-test/CMock/src/cmock.s: unit-test/CMock/src/cmock.c.s
.PHONY : unit-test/CMock/src/cmock.s

# target to generate assembly for a file
unit-test/CMock/src/cmock.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmock.dir/build.make CMakeFiles/cmock.dir/unit-test/CMock/src/cmock.c.s
.PHONY : unit-test/CMock/src/cmock.c.s

unit-test/CMock/vendor/unity/extras/fixture/src/unity_fixture.o: unit-test/CMock/vendor/unity/extras/fixture/src/unity_fixture.c.o
.PHONY : unit-test/CMock/vendor/unity/extras/fixture/src/unity_fixture.o

# target to build an object file
unit-test/CMock/vendor/unity/extras/fixture/src/unity_fixture.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unity.dir/build.make CMakeFiles/unity.dir/unit-test/CMock/vendor/unity/extras/fixture/src/unity_fixture.c.o
.PHONY : unit-test/CMock/vendor/unity/extras/fixture/src/unity_fixture.c.o

unit-test/CMock/vendor/unity/extras/fixture/src/unity_fixture.i: unit-test/CMock/vendor/unity/extras/fixture/src/unity_fixture.c.i
.PHONY : unit-test/CMock/vendor/unity/extras/fixture/src/unity_fixture.i

# target to preprocess a source file
unit-test/CMock/vendor/unity/extras/fixture/src/unity_fixture.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unity.dir/build.make CMakeFiles/unity.dir/unit-test/CMock/vendor/unity/extras/fixture/src/unity_fixture.c.i
.PHONY : unit-test/CMock/vendor/unity/extras/fixture/src/unity_fixture.c.i

unit-test/CMock/vendor/unity/extras/fixture/src/unity_fixture.s: unit-test/CMock/vendor/unity/extras/fixture/src/unity_fixture.c.s
.PHONY : unit-test/CMock/vendor/unity/extras/fixture/src/unity_fixture.s

# target to generate assembly for a file
unit-test/CMock/vendor/unity/extras/fixture/src/unity_fixture.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unity.dir/build.make CMakeFiles/unity.dir/unit-test/CMock/vendor/unity/extras/fixture/src/unity_fixture.c.s
.PHONY : unit-test/CMock/vendor/unity/extras/fixture/src/unity_fixture.c.s

unit-test/CMock/vendor/unity/extras/memory/src/unity_memory.o: unit-test/CMock/vendor/unity/extras/memory/src/unity_memory.c.o
.PHONY : unit-test/CMock/vendor/unity/extras/memory/src/unity_memory.o

# target to build an object file
unit-test/CMock/vendor/unity/extras/memory/src/unity_memory.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unity.dir/build.make CMakeFiles/unity.dir/unit-test/CMock/vendor/unity/extras/memory/src/unity_memory.c.o
.PHONY : unit-test/CMock/vendor/unity/extras/memory/src/unity_memory.c.o

unit-test/CMock/vendor/unity/extras/memory/src/unity_memory.i: unit-test/CMock/vendor/unity/extras/memory/src/unity_memory.c.i
.PHONY : unit-test/CMock/vendor/unity/extras/memory/src/unity_memory.i

# target to preprocess a source file
unit-test/CMock/vendor/unity/extras/memory/src/unity_memory.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unity.dir/build.make CMakeFiles/unity.dir/unit-test/CMock/vendor/unity/extras/memory/src/unity_memory.c.i
.PHONY : unit-test/CMock/vendor/unity/extras/memory/src/unity_memory.c.i

unit-test/CMock/vendor/unity/extras/memory/src/unity_memory.s: unit-test/CMock/vendor/unity/extras/memory/src/unity_memory.c.s
.PHONY : unit-test/CMock/vendor/unity/extras/memory/src/unity_memory.s

# target to generate assembly for a file
unit-test/CMock/vendor/unity/extras/memory/src/unity_memory.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unity.dir/build.make CMakeFiles/unity.dir/unit-test/CMock/vendor/unity/extras/memory/src/unity_memory.c.s
.PHONY : unit-test/CMock/vendor/unity/extras/memory/src/unity_memory.c.s

unit-test/CMock/vendor/unity/src/unity.o: unit-test/CMock/vendor/unity/src/unity.c.o
.PHONY : unit-test/CMock/vendor/unity/src/unity.o

# target to build an object file
unit-test/CMock/vendor/unity/src/unity.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unity.dir/build.make CMakeFiles/unity.dir/unit-test/CMock/vendor/unity/src/unity.c.o
.PHONY : unit-test/CMock/vendor/unity/src/unity.c.o

unit-test/CMock/vendor/unity/src/unity.i: unit-test/CMock/vendor/unity/src/unity.c.i
.PHONY : unit-test/CMock/vendor/unity/src/unity.i

# target to preprocess a source file
unit-test/CMock/vendor/unity/src/unity.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unity.dir/build.make CMakeFiles/unity.dir/unit-test/CMock/vendor/unity/src/unity.c.i
.PHONY : unit-test/CMock/vendor/unity/src/unity.c.i

unit-test/CMock/vendor/unity/src/unity.s: unit-test/CMock/vendor/unity/src/unity.c.s
.PHONY : unit-test/CMock/vendor/unity/src/unity.s

# target to generate assembly for a file
unit-test/CMock/vendor/unity/src/unity.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unity.dir/build.make CMakeFiles/unity.dir/unit-test/CMock/vendor/unity/src/unity.c.s
.PHONY : unit-test/CMock/vendor/unity/src/unity.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... Continuous"
	@echo "... ContinuousBuild"
	@echo "... ContinuousConfigure"
	@echo "... ContinuousCoverage"
	@echo "... ContinuousMemCheck"
	@echo "... ContinuousStart"
	@echo "... ContinuousSubmit"
	@echo "... ContinuousTest"
	@echo "... ContinuousUpdate"
	@echo "... Experimental"
	@echo "... ExperimentalBuild"
	@echo "... ExperimentalConfigure"
	@echo "... ExperimentalCoverage"
	@echo "... ExperimentalMemCheck"
	@echo "... ExperimentalStart"
	@echo "... ExperimentalSubmit"
	@echo "... ExperimentalTest"
	@echo "... ExperimentalUpdate"
	@echo "... Nightly"
	@echo "... NightlyBuild"
	@echo "... NightlyConfigure"
	@echo "... NightlyCoverage"
	@echo "... NightlyMemCheck"
	@echo "... NightlyMemoryCheck"
	@echo "... NightlyStart"
	@echo "... NightlySubmit"
	@echo "... NightlyTest"
	@echo "... NightlyUpdate"
	@echo "... coverage"
	@echo "... cmock"
	@echo "... core_mqtt_mock"
	@echo "... core_mqtt_real"
	@echo "... core_mqtt_serializer_utest"
	@echo "... core_mqtt_state_utest"
	@echo "... core_mqtt_utest"
	@echo "... core_mqttv5_mock"
	@echo "... core_mqttv5_real"
	@echo "... core_mqttv5_serializer_utest"
	@echo "... core_mqttv5_state_utest"
	@echo "... core_mqttv5_utest"
	@echo "... coverity_analysis"
	@echo "... unity"
	@echo "... source/core_mqtt.o"
	@echo "... source/core_mqtt.i"
	@echo "... source/core_mqtt.s"
	@echo "... source/core_mqtt_serializer.o"
	@echo "... source/core_mqtt_serializer.i"
	@echo "... source/core_mqtt_serializer.s"
	@echo "... source/core_mqtt_state.o"
	@echo "... source/core_mqtt_state.i"
	@echo "... source/core_mqtt_state.s"
	@echo "... unit-test/CMock/src/cmock.o"
	@echo "... unit-test/CMock/src/cmock.i"
	@echo "... unit-test/CMock/src/cmock.s"
	@echo "... unit-test/CMock/vendor/unity/extras/fixture/src/unity_fixture.o"
	@echo "... unit-test/CMock/vendor/unity/extras/fixture/src/unity_fixture.i"
	@echo "... unit-test/CMock/vendor/unity/extras/fixture/src/unity_fixture.s"
	@echo "... unit-test/CMock/vendor/unity/extras/memory/src/unity_memory.o"
	@echo "... unit-test/CMock/vendor/unity/extras/memory/src/unity_memory.i"
	@echo "... unit-test/CMock/vendor/unity/extras/memory/src/unity_memory.s"
	@echo "... unit-test/CMock/vendor/unity/src/unity.o"
	@echo "... unit-test/CMock/vendor/unity/src/unity.i"
	@echo "... unit-test/CMock/vendor/unity/src/unity.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

