name: Memory statistics

on:
  workflow_dispatch:

jobs:
  memory_statistics:
    name: Calculate object sizes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
            submodules: 'recursive'
      - name: Measure sizes
        uses: FreeRTOS/CI-CD-Github-Actions/memory_statistics@main
        with:
            config: .github/memory_statistics_config.json
      - name: Upload table
        uses: actions/upload-artifact@v2
        with:
          name: size_table
          path: size_table.html
